apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
        - name: glpi
          image: phumthanarat/glpi-dev:latest   # 👈 สำคัญ
          ports:
            - containerPort: 80
